### ISSUE TITLE
Unable to run plandex

### ISSUE THREAD

**Issue by jefferyokesamuel** [plandex-ai/plandex#127]
I've tried switching models but I keep getting an error about exceeding my OpenAI quota, even for a new account
<img width="906" alt="Screenshot 2024-05-18 at 6 44 23 AM" src="https://github.com/plandex-ai/plandex/assets/31242671/affb455f-6ba7-4f7a-8799-f41543440c07">

**Comment by danenania** [comment]
Hi @jefferyokesamuel, this likely means you're either using the wrong API key (try `echo OPENAI_API_KEY` to make sure it's the one you expect), or that you're out of OpenAI credits.

**Comment by atljoseph** [comment]
I got this error at first too, even though nothing seemed off in the account. I think you just have to put in $$. My admin signed us up for the billing where you put in $10 and it re-ups to $10 after you get to $5 and the problem went away. Now just having intermittent 429s since it blasts all its traffic at OpenAI by default. 

To see that plandex is or is not the problem, download the FREE AnythingLLM desktop app. Plug in your api key and hit send. It should show rate limited there if it isn’t plandex.
