### ISSUE TITLE
Bypass SMTP config in self-hosted plandex using docker-compose

### ISSUE THREAD

**Issue by aakashb09** [plandex-ai/plandex#80]
I don't have an SMTP server/SendGrid config, but I want to be able to run it without those. It fails on me for an invalid PIN/email.
<img width="409" alt="image" src="https://github.com/plandex-ai/plandex/assets/122796493/7df1c876-cddb-49f9-a528-20031d174424">

**Comment by Dexus** [comment]
setup a mailhog server within a docker-compose setup, and you can setup a mail server so you dont get this error or you can get your mails in a webui, without really send them over the network

**Comment by Dexus** [comment]
If you looking to your server logs, you will also be able to see the token/code to verify.

**Comment by danenania** [comment]
Hi @aakashb09, if you set `GOENV=development` when running the server, it will copy the pin to clipboard and output it to the console rather than sending by email, so you don't need SMTP settings.

Someone did report an issue in the discord recently that looked like this. It sounded like possibly a mismatch between timestamps in the Go server code and PostgreSQL. I'll investigate.

**Comment by aakashb09** [comment]
>If you looking to your server logs, you will also be able to see the token/code to verify.
This worked for me

> It sounded like possibly a mismatch between timestamps in the Go server code and PostgreSQL.
Doesn't look like, at least for me. 

Thanks for the help, closing this.
